<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Data Generation

_Author: Tim Book_

---

If you accidentally edit or delete the provided data, feel free to use this script to repopulate it. Note that you don't ever actually need this, as you can always re-access the data by cloning it again.

In [1]:
import numpy as np
import pandas as pd
import sqlite3
from faker import Faker
import hashlib

In [2]:
f = Faker()

def to_id(s):
    return hashlib.sha256(s.encode('utf8')).hexdigest()[-16:]

### Users

In [3]:
f.seed_instance(1)

N_USERS = 200

users = pd.DataFrame({
    'first': [f.first_name() for _ in range(N_USERS)],
    'last': [f.last_name() for _ in range(N_USERS)]
})

users['email'] = (users['first'] + '.' + users['last'] + "@gmail.com").str.lower()
users['user_id'] = users.email.apply(to_id)

### Payment Methods

In [4]:
f.seed_instance(2)

N_PAY = 250

payment_methods = pd.DataFrame({
    'cc_number': [f.credit_card_number() for _ in range(N_PAY)],
    'cc_expire': [f.credit_card_expire() for _ in range(N_PAY)],
    'cc_security': [f.credit_card_security_code() for _ in range(N_PAY)],
})

user_ids = users.user_id.unique().tolist()

payment_methods['user_id'] = np.append(
    np.random.choice(user_ids, N_USERS, replace=False),
    np.random.choice(user_ids, N_PAY - N_USERS, replace=True),
)

### Characters and Guilds

In [5]:
# Generated with ChatGPT

char_names = pd.Series(list(set([
    "Arinthor", "Vylora", "Zyphera", "Kaelus", "Thalara", "Nymor", "Elowen", "Dragmar", "Falor",
    "Lysara", "Vyrn", "Zaric", "Thalindor", "Sariel", "Brevin", "Aylara", "Zephyris", "Rylorin",
    "Morwyn", "Tharion", "Elindra", "Korrin", "Nyssara", "Orinthal", "Valeria", "Sylaris", "Dralin",
    "Isilwen", "Thyros", "Selara", "Kaelen", "Fynril", "Lyrian", "Ardella", "Torvyn", "Vesryn", "Marisara",
    "Druvor", "Lirael", "Vyris", "Thandor", "Zerith", "Aeloria", "Nyras", "Kelindra", "Sorath", "Eldrin",
    "Thalara", "Valtor", "Zylara", "Orinthar", "Iseldra", "Draegan", "Kalindra", "Rynor", "Sylara",
    "Thrynn", "Lorwyn", "Zyrel", "Aelindra", "Thrandor", "Velorin", "Rylan", "Kethor", "Zariel", "Marianis",
    "Kyros", "Thalara", "Zorvyn", "Selindra", "Elyndor", "Vystra", "Thalios", "Karion", "Lorath", "Nymira",
    "Draelor", "Alindra", "Sorvin", "Vyrn", "Elthar", "Zephira", "Rylandor", "Thalaria", "Vynra", "Morven",
    "Zalindra", "Korrath", "Thyrian", "Aelorin", "Selyn", "Darion", "Vylara", "Thandar", "Marisandra",
    "Zyrion", "Kalthar", "Soriel", "Valyndra", "Elorn", "Thalindra", "Zarion", "Vesindra", "Rythor",
    "Thalara", "Nyssara", "Kyndor", "Thryndor", "Vylora", "Zaloria", "Arinor", "Selena", "Kelvar", "Vystra",
    "Thaloria", "Sarinth", "Dragorin", "Kaeloria", "Zaril", "Orion", "Vyndra", "Thalir", "Althara",
    "Sorwyn", "Lysar", "Valindra", "Zoran", "Kalira", "Rynal", "Thalindra", "Vesrin", "Korin", "Zylorin",
    "Marionis", "Vyris", "Thaldor", "Lyrel", "Elthorin", "Soren", "Aranth", "Torwin", "Vylindra", "Tharion",
    "Zalindra", "Morath", "Kallindra", "Ryndor", "Thalindra", "Vystra", "Zerion", "Elorn", "Thalira",
    "Kylandra", "Soroth", "Valorian", "Lyris", "Tharion", "Zorvin", "Kalindra", "Rylan", "Sarinth",
    "Draelin", "Althar", "Thalindra", "Vylorin", "Zandor", "Torwin", "Kyndra", "Thrandor", "Selorin",
    "Valeria", "Zylar", "Ardella", "Thalorian", "Vesindra", "Rylorin", "Korrin", "Thalara",
    "Morin", "Zephyra", "Arinthal", "Vylara", "Zoran", "Kallora", "Syloria", "Thorin", "Valindra",
    "Zerith", "Kalorin", "Thalira", "Sarwyn", "Draelin", "Lirion", "Vystra", "Thalindor", "Zorvin",
    "Toriel", "Valethor", "Kyndra", "Thrandor", "Selara", "Arion", "Thalara", "Zyrel", "Vysrin", "Lorath",
    "Thrynn", "Zelara", "Korith", "Thalor", "Sarin", "Vyris", "Lynara", "Zorath", "Thrandor", "Kelion",
    "Sylora", "Valeth", "Zyrel", "Kalorin", "Thalindra", "Rynal", "Torvin", "Valeryn", "Lorith", "Sariel",
    "Zorvin", "Kallin", "Thariel", "Vylorin", "Zephyra", "Arinthor", "Selin", "Thalara", "Zylora",
    "Korrin", "Thrandor", "Lysarin", "Zoran", "Marion", "Thalira", "Vysrin", "Aranth", "Selwyn",
    "Thalor", "Vylora", "Zyphera", "Lorin", "Sariel", "Koryn", "Thrandor",
    "Eldrin", "Nyxora", "Thandor", "Vesryn", "Kalira", "Orin", "Sylvara", "Zalric", "Lorwyn",
    "Thalindra", "Varyn", "Zythera", "Kylorin", "Elora", "Sorath", "Valorian", "Thalrin", "Rynara",
    "Zephirin", "Vesara", "Thrandir", "Nyssorin", "Korith", "Lynora", "Zoranis", "Eldara", "Vylara",
    "Thalon", "Kalindra", "Marwyn", "Selara", "Orinthor", "Thalvar", "Sorwen", "Valira", "Nythera",
    "Zarion", "Lirael", "Thrandor", "Vesindra", "Kylorin", "Elyndra", "Thaleth", "Valindra", "Soryn",
    "Zorath", "Lyrion", "Tharwyn", "Vynara", "Kalora", "Nyxorin", "Thalindor", "Ryndra", "Zylora",
    "Saryn", "Eldoris", "Vesara", "Thalindra", "Torvyn", "Zorwin", "Lorian", "Sorath", "Kallindra",
    "Vysrin", "Thalwyn", "Nytherin", "Zeloria", "Lyndra", "Thrandir", "Valyra", "Vylora", "Korvin",
    "Tharion", "Sorwin", "Lythor", "Zephira", "Orionis", "Thaleth", "Valrynn", "Sorwin", "Zalira",
    "Elvorin", "Vesryn", "Thalor", "Nyssara", "Zyloris", "Lorian", "Thariel", "Vyrin", "Korath",
    "Sarinth", "Zoriel", "Lysara", "Eldris", "Vystra", "Thalir"
])))

guild_names = pd.Series([
    "The Silver Serpents", "Blades of Valoria", "The Ebon Circle", "Order of the Phoenix",
    "Moonshadow Brotherhood", "The Ironclad", "Shadowveil Assassins", "Guardians of the Dawn",
    "Crimson Covenant", "The Night Watchers", "Emerald Enclave", "The Arcane Brotherhood",
    "Stormriders", "The Whispering Blades", "Frostborn Vanguard", "The Shattered Shields",
    "Lunar Sentinels", "The Bloodsworn", "Celestial Vanguard", "The Onyx Order",
    "The Gilded Hawks", "Dragonheart Syndicate", "The Sunfire Legion", "Wraithwalkers",
    "The Rune Keepers", "Obsidian Order", "The Silent Hand", "The Stormbound", "The Ashen Wolves",
    "The Verdant Cloaks"
])

In [6]:
class_names = [
    'warrior', 'mage', 'rogue', 'paladin', 'ranger',
    'cleric', 'druid', 'necromancer', 'bard', 'warlock'
]

In [7]:
np.random.seed(789) 

N_CHARS = len(char_names)

characters = pd.DataFrame({
    'character_name': char_names,
    'xp': np.random.randint(100, 10_000, N_CHARS),
    'gold': np.random.randint(0, 100_000, N_CHARS),
    'guild': np.random.choice(guild_names, N_CHARS)
})

characters['level'] = characters.xp // 350 + 1
characters.loc[np.random.choice(np.arange(N_CHARS), N_CHARS // 10), 'guild'] = np.nan
characters['character_id'] = characters.character_name.apply(to_id)
characters['guild_id'] = characters.guild.astype(str).apply(to_id)
characters['guild_id'] = np.where(characters['guild'].isna(), np.nan, characters['guild_id'])
characters['class'] = [', '.join(np.random.choice(class_names, np.random.randint(1, 3)).tolist()) for _ in range(N_CHARS)]

characters['user_id'] = np.append(
    np.random.choice(user_ids, N_USERS, replace=False),
    np.random.choice(user_ids, N_CHARS - N_USERS, replace=True),
)

### Join to OBT

In [8]:
res = characters \
    .merge(users, how='outer', on='user_id') \
    .merge(payment_methods, on='user_id')

In [9]:
res.head()

,character_name,xp,gold,guild,level,character_id,guild_id,class,user_id,first,last,email,cc_number,cc_expire,cc_security
0,Arinthal,4759,6337,Blades of Valoria,14,3637b0973159e0f9,e9c3b0d506c11b1c,"ranger, bard",27f03e4c3c73b776,William,English,william.english@gmail.com,4332902193345137,01/26,188
1,Darion,1778,52334,Shadowveil Assassins,6,9bb0a13051ff749a,52f6902bcca61a6a,druid,b0c42a8323d7bd33,Dawn,Jones,dawn.jones@gmail.com,3505787210639965,04/33,202
2,Orinthor,4475,60097,Guardians of the Dawn,13,35f0ede436c0dc11,9ef1a491982cbf06,"paladin, cleric",b0c42a8323d7bd33,Dawn,Jones,dawn.jones@gmail.com,3505787210639965,04/33,202
3,Zephira,1955,92548,Dragonheart Syndicate,6,9774f1bd1793c7c6,d96e0324970f052f,"rogue, rogue",b0c42a8323d7bd33,Dawn,Jones,dawn.jones@gmail.com,3505787210639965,04/33,202
4,Kalthar,6117,33505,Stormriders,18,ee0f7ff461e2673c,8f988bdc8e02453c,"necromancer, ranger",f9dd9b9640387403,Crystal,Weaver,crystal.weaver@gmail.com,2532469005140959,08/29,106

### Order Columns

In [10]:
col_order = [
    'character_id', 'character_name', 'xp', 'level', 'gold', 'class',
    'guild_id', 'guild',
    'user_id', 'first', 'last', 'email', 
    'cc_number', 'cc_expire', 'cc_security'
]

res[col_order].head()

,character_id,character_name,xp,level,gold,class,guild_id,guild,user_id,first,last,email,cc_number,cc_expire,cc_security
0,3637b0973159e0f9,Arinthal,4759,14,6337,"ranger, bard",e9c3b0d506c11b1c,Blades of Valoria,27f03e4c3c73b776,William,English,william.english@gmail.com,4332902193345137,01/26,188
1,9bb0a13051ff749a,Darion,1778,6,52334,druid,52f6902bcca61a6a,Shadowveil Assassins,b0c42a8323d7bd33,Dawn,Jones,dawn.jones@gmail.com,3505787210639965,04/33,202
2,35f0ede436c0dc11,Orinthor,4475,13,60097,"paladin, cleric",9ef1a491982cbf06,Guardians of the Dawn,b0c42a8323d7bd33,Dawn,Jones,dawn.jones@gmail.com,3505787210639965,04/33,202
3,9774f1bd1793c7c6,Zephira,1955,6,92548,"rogue, rogue",d96e0324970f052f,Dragonheart Syndicate,b0c42a8323d7bd33,Dawn,Jones,dawn.jones@gmail.com,3505787210639965,04/33,202
4,ee0f7ff461e2673c,Kalthar,6117,18,33505,"necromancer, ranger",8f988bdc8e02453c,Stormriders,f9dd9b9640387403,Crystal,Weaver,crystal.weaver@gmail.com,2532469005140959,08/29,106

### Write

In [12]:
res.to_csv('../data/dsb-full-data.csv', index=False)